<?php 

if( !empty($_POST) ) {
    var_dump( $_POST );
    \Application\Model\SendEmail::send([
        'to' => 'kaiofhs@gmail.com',
        'from' => 'victtor.lima@soluti.com.br',
        'subject' => 'Do Form',
        'mensage' => $_POST['Texto'],
    ]);
}

class Form_Contato extends Zend\Form\Form {

    public function __construct()
    {
        parent::__construct();

        $this->add( [
            'name' => 'username',
            'type' => Zend\Form\Element\Text::class,
            'options' => [
                'label' => 'Nome'
            ],
            'attributes' => [
                'id' => 'username',
                'class' => 'form-control'
            ]
        ] );
        $this->add( [
            'name' => 'Email',
            'type' => Zend\Form\Element\Text::class,
            'options' => [
                'label' => 'Email'
            ],
            'attributes' => [
                'id' => 'Email',
                'class' => 'form-control'
            ]
        ] );
        $this->add( [
            'name' => 'Texto',
            'type' => Zend\Form\Element\Textarea::class,
            'options' => [
                'label' => 'Texto'
            ],
            'attributes' => [
                'id' => 'Texto',
                'class' => 'form-control'
            ]
        ] );
        $this->add( [
            'name' => 'submit',
            'type' => Zend\Form\Element\Submit::class,
            'attributes' => [
                'id' => 'submit',
                'value' => 'Enviar',
                'class' => 'btn btn-success'
            ]
        ] );
    }
}




$form = new Form_Contato();

?>

<div class="jumbotron">
    <?php echo $this->form( $form ); ?>
</div>



