<?php 

class Form_Galeria extends Zend\Form\Form {

    public function __construct()
    {
        parent::__construct();

        $this->add( [
            'name' => 'descricao',
            'type' => Zend\Form\Element\Text::class,
            'options' => [
                'label' => 'Descrição'
            ],
            'attributes' => [
                'id' => 'descricao',
                'class' => 'form-control'
            ]
        ] );

        $this->add( [
            'name' => 'arquivo',   
            'type' => Zend\Form\Element\File::class,
            'options' => [
                'label' => 'Arquivo'
            ],
            'attributes' => [
                'id' => 'arquivo',
                'class' => 'form-control'
            ]
        ] );
        
        $this->add( [
            'name' => 'submit',
            'type' => Zend\Form\Element\Submit::class,
            'attributes' => [
                'id' => 'submit',
                'value' => 'Enviar',
                'class' => 'btn btn-success'
            ]
        ] );
    }
}

$form = new Form_Galeria();

$form->prepare(); 

?>

<div class="jumbotron">
    <?php
        
        if( $this->fileErrors != NULL ) {
            if( empty( $this->fileErrors ) ) {
                echo 'Upload realizada com sucesso!';
            } else {
                echo 'Upload não aconteceu pelos seguintes erros: '.implode( ' | ', $this->fileErrors);
            }
        }
        
    ?>
    <?php echo $this->form( $form ); ?>
</div>

